### ISSUE TITLE
Use of unresolved identifier 'PageDataSettings'

### ISSUE THREAD

**Issue by mck694** [congncif/PagingDataController#1]
On installing it is giving this error.

**Comment by congncif** [comment]
Which version are you using? This class `PageDataSettings` was removed in latest version. Please upgrade!

**Comment by mck694** [comment]
> Which version are you using? This class `PageDataSettings` was removed in latest version. Please upgrade!

**Comment by mck694** [comment]
Use of unresolved identifier 'PageDataSettings' 
And both PagingDataController and PagingDataControllerExtension are Swift 4.2
![Screen Shot 2019-07-11 at 12 40 15 PM](https://user-images.githubusercontent.com/32296057/61029691-38f01680-a3d9-11e9-9c52-add817da39ba.png)
![Screen Shot 2019-07-11 at 12 40 53 PM](https://user-images.githubusercontent.com/32296057/61029692-38f01680-a3d9-11e9-90cf-1d50ec057c63.png)
![Screen Shot 2019-07-11 at 12 41 01 PM](https://user-images.githubusercontent.com/32296057/61029693-3988ad00-a3d9-11e9-974a-011db75294d8.png)

**Comment by congncif** [comment]
*PagingDataControllerExtension* framework was deprecated and moved to original framework. Just use *PagingDataController* enough. Some protocols were changed so you should clone repo *PagingDataController* and see more in Example.
