### ISSUE TITLE
Is it possible to remove an element of the tableView?

### ISSUE THREAD

**Issue by jarrillaga** [congncif/PagingDataController#2]
@congncif I'm not finding a way to remove an element from the datasource after getting the information. Suppose, that the user can swipe a row and remove it. Is it possible ?

**Comment by congncif** [comment]
@jarrillaga No. Datasource from `PageDataController` is immutable rawData. If you want to custom displaying, you should map to a `displayedObjects` then mutate it. Implement method of `PageDataSourceDelegate` to update `displayedObjects` if needed.
